### ISSUE TITLE
[Fix] Error on First Page load if not logged in

### ISSUE THREAD

**Issue by pixhy** [RizzyApp/rizzy#101]
![Image](https://github.com/user-attachments/assets/ade8c09a-0385-4ce1-8001-2f57433d17dc)

```
fail: API.Services.SignalR.CustomUserIdProvider[0]
      Failed to resolve userId for SignalR connection
      System.AggregateException: One or more errors occurred. (User is not authorized)
       ---> API.Utils.Exceptions.MissingClaimException: User is not authorized
         at API.Services.UserService.GetUserByIdentityIdAsync(ClaimsPrincipal userClaims) in D:\Codecool\projects\advanced\rizzy\server\API\Services\UserService.cs:line 27
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
         at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
         at API.Services.SignalR.CustomUserIdProvider.GetUserId(HubConnectionContext connection) in D:\Codecool\projects\advanced\rizzy\server\API\Services\SignalR\CustomUserIdProvider.cs:line 23
fail: API.Services.SignalR.CustomUserIdProvider[0]
      Failed to resolve userId for SignalR connection
      System.AggregateException: One or more errors occurred. (User is not authorized)
       ---> API.Utils.Exceptions.MissingClaimException: User is not authorized
         at API.Services.UserService.GetUserByIdentityIdAsync(ClaimsPrincipal userClaims) in D:\Codecool\projects\advanced\rizzy\server\API\Services\UserService.cs:line 27
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
         at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
         at API.Services.SignalR.CustomUserIdProvider.GetUserId(HubConnectionContext connection) in D:\Codecool\projects\advanced\rizzy\server\API\Services\SignalR\CustomUserIdProvider.cs:line 23

```

**Comment by hegedus-mark** [comment]
This shouldn't cause any issues, SignalR will try to connect and if it can't it will stop attempting to reconnect

**Comment by pixhy** [comment]
Throwing an error for unauthenticated requests might not break functionality, but it suggests a design issue. It's better to handle this case explicitly (e.g., returning a 401 Unauthorized) to ensure the server is robust and clean. 🛠️✨
